spring.application.name=todolistapi

spring.datasource.url=jdbc:mysql://localhost:3306/todolist
spring.datasource.username=root
spring.datasource.password=TROUBADOR!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.security-key=de452b9d3194dae918836fa6ff640fdc42b2a6e30dd17b51fa8e0b865279d102
security.jwt.expiration-time=3600000